{
 "title": "Noise Buster Demo",
 "description": "monitoring of illegal (above 80dB) noise levels generated by traffic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total illegal noises (over 80dB) last 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"noise_buster_events\" and r.location == \"noise_buster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"_value\"] >= 80)\n  |> drop(columns: [\"vehicle_type\"])\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total illegal noises (over 80dB) last week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r._measurement == \"noise_buster_events\" and r.location == \"noise_buster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"_value\"] >= 80)\n  |> drop(columns: [\"vehicle_type\"])\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 0 },
   "options": {
    "content": "\n\n<img src=\"https://cc-prod.scene7.com/is/image/CCProdAuthor/AdobeStock_177246214-desktop?$pjpeg$&jpegSize=200&wid=690\"/>"
   }
  },
  {
   "title": "Total illegal noises (over 80dB) last month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"noise_buster_events\" and r.location == \"noise_buster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"_value\"] >= 80)\n  |> drop(columns: [\"vehicle_type\"])\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Real-time noise levels",
   "type": "timeseries",
   "description": "noise levels generated by truckers and bikers (mostly) on Montefiore axis",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "noise_levels_montefiore_influxdb",
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"noise_buster_events\" and r.location == \"noise_buster\")\n  |> sort(columns: [\"_time\"])\n",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Max noise level (last 24h)",
   "type": "gauge",
   "description": "Highest noise level",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n|> range(start: -24h, stop: now())\n|> filter(fn: (r) => r._measurement == \"noise_buster_events\" and r.location == \"noise_buster\")\n|> filter(fn: (r) => r[\"_field\"] == \"level\")\n|> drop(columns: [\"vehicle_type\"])\n|> max(column: \"_value\")\n\n"
    }
   ]
  },
  {
   "title": "Max noise level (last month)",
   "type": "gauge",
   "description": "Highest noise level",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r._measurement == \"noise_buster_events\" and r.location == \"noise_buster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> drop(columns: [\"vehicle_type\"])\n  |> max(column: \"_value\")\n\n\n"
    }
   ]
  },
  {
   "title": "Max noise level (last week)",
   "type": "gauge",
   "description": "Highest noise level",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -7d, stop: now())\n  |> filter(fn: (r) => r._measurement == \"noise_buster_events\" and r.location == \"noise_buster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> drop(columns: [\"vehicle_type\"])\n  |> max(column: \"_value\")\n\n\n"
    }
   ]
  },
  {
   "title": "% per infraction / dB level (last 24h)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"noise_buster\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_buster_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"location\"] == \"noise_buster\")\n  |> map(fn: (r) => ({_time: r[\"_time\"], value: r[\"_value\"],\n                      noise_level: if r[\"_value\"] >= 80 and r[\"_value\"] <= 85 then \"80-85dB\"\n                             else if r[\"_value\"] >= 85.1 and r[\"_value\"] <= 90 then \"86-90dB\"\n                             else if r[\"_value\"] >= 90.1 and r[\"_value\"] <= 95 then \"91-95dB\"\n                             else if r[\"_value\"] >= 95.1 and r[\"_value\"] <= 100 then \"96-100dB\"\n                             else if r[\"_value\"] >= 100.1 and r[\"_value\"] <= 105 then \"100-105dB\"\n                             else if r[\"_value\"] >= 105.1 and r[\"_value\"] <= 110 then \"105-110dB\"\n                             else if r[\"_value\"] >= 110.1 and r[\"_value\"] <= 115 then \"110-115dB\"\n                             else if r[\"_value\"] > 115.1 then \"115+dB\"\n                             else \"Other\"}))\n  |> drop(columns: [\"vehicle_type\"])\n  |> group(columns: [\"noise_level\"])"
    }
   ]
  },
  {
   "title": "Amount of illegal noises per hour (last 24h)",
   "type": "barchart",
   "description": "here we see the amount of illegal noise events happening each hour",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_buster_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"location\"] == \"noise_buster\")\n  |> filter(fn: (r) => r._value > 80)\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: false)\n  |> drop(columns: [\"vehicle_type\"])\n  |> yield(name: \"count_over_80\")\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Amount of illegal noises per day (last week)",
   "type": "barchart",
   "description": "here we see the amount of illegal noise events happening each hour",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_buster_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"location\"] == \"noise_buster\")\n  |> filter(fn: (r) => r._value > 80)\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: false)\n  |> drop(columns: [\"vehicle_type\"])\n  |> yield(name: \"count_over_80_per_day\")\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Amount of illegal noises per week (sunny = more)",
   "type": "barchart",
   "description": "here we see the amount of illegal noise events happening each hour",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_buster_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"location\"] == \"noise_buster\")\n  |> filter(fn: (r) => r._value > 80)\n  |> aggregateWindow(every: 1w, fn: count, createEmpty: false)\n  |> drop(columns: [\"vehicle_type\"])\n  |> yield(name: \"count_over_80_per_day\")\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Amount of illegal noises per month (sunny = more)",
   "type": "barchart",
   "description": "here we see the amount of illegal noise events happening each hour",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_buster_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"location\"] == \"noise_buster\")\n  |> filter(fn: (r) => r._value > 80)\n  |> aggregateWindow(every: 1mo, fn: count, createEmpty: false)\n  |> drop(columns: [\"vehicle_type\"])\n  |> yield(name: \"count_over_80_per_day\")\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Max illegal noise levels per hour (last 24h)",
   "type": "barchart",
   "description": "here we see the max noise levels happening each hour",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "noise_levels_montefiore_influxdb",
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_buster_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"location\"] == \"noise_buster\")\n  |> aggregateWindow(every: 1h, fn: max, createEmpty: false)\n  |> drop(columns: [\"vehicle_type\"])\n  |> yield(name: \"max_level_per_hour\")\n\n",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max illegal noise levels per day (last 7 days)",
   "type": "barchart",
   "description": "here we check on which days noise levels are the highest (on Sundays, bikers are out...)",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"noise_buster\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"noise_buster_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level\")\n  |> filter(fn: (r) => r[\"location\"] == \"noise_buster\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> drop(columns: [\"vehicle_type\"])\n  |> yield(name: \"max_level_per_day\")\n\n\n"
    }
   ]
  }
 ]
}